[tool.poetry]
name = "sphinx_readthedocs_test"
version = "0.1.0"
description = ""
authors = ["Alamden Genomics, 2022"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"